### ISSUE TITLE
Returning error instead of panic

### ISSUE THREAD

**Issue by rosenhouse** [alexflint/go-filemutex#3]
Hi,

We're looking at using this library to provide cross-platform file-locking in a CNI Plugin (see https://github.com/containernetworking/plugins/pull/77).

I see several methods panic on error rather than returning the error to the caller.

*Effective Go* recommends 

> real library functions should avoid `panic`

[[reference](https://golang.org/doc/effective_go.html#panic)]

Would you be open to a PR that changes the signatures of the functions to return errors?

**Comment by alexflint** [comment]
The original thinking here was to exactly match the signature of the methods on `sync.Mutex` and `sync.RWMutex`, in order to make it possible to write interfaces that close around those methods.

In retrospect I think you're right and that these methods should return errors. I'd happily accept a pr.
